# Permalinks
#
# Setup
title:               Samy Arous
tagline:             "A developer's journey"
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://samyarous.github.io/
baseurl:             ''
paginate:            5
# About/contact
author:
  name:              Sami Arous
  email:             samy.arous@gmail.com

# Custom vars
version:             1.0.0

show_dir_listing: false
timezone:      Europe/Amsterdam

gems: [jekyll-paginate]